### ISSUE TITLE
Error handling for bad api calls

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-aggregate-check#13]
When passing bad configurations, the errors returned are not helpful. This may be due to error handling from responses coming from the api. 

As an example configuring `--api-pass=notthecorrectpassword` will return in my use case:
```
Error executing sensu-aggregate-check: error executing check: invalid character 'U' looking for beginning of value
```
While configured with the correct password the check works correctly.

**Comment by nixwiz** [comment]
The 'U' is because it's expecting a JSON response back with the access token, but is instead getting only the text 'Unauthorized'.

We can definitely add something to at least catch that and surface it better.
